# yaml 配置
version: '3'

networks:
  backend:
    driver: bridge

# 服务
services:
  golang:
    build:
      context: ./golang
      # dockerfile: ./Dockerfile
    environment:                         # 设置环境变量
      - TZ=Asia/Shanghai
    volumes:                             # 设置挂载目录
      - ./code:/usr/src/code  # 引用 .env 配置中 CODE_PATH_HOST 变量，将宿主机上代码存放的目录挂载到容器中 /usr/src/code 目录
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - backend
    ports:                               # 设置端口映射
      - "9090:8080"

  mysql:
    build:
      context: ./mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=admin                  # 设置 Mysql 用户名称
      - MYSQL_PASSWORD=123456              # 设置 Mysql 用户密码
      - MYSQL_ROOT_PASSWORD=123456    # 设置 Mysql root 用户密码
    volumes:
      - ./data:/var/lib/mysql        # 将宿主机上存放 Mysql 数据的目录挂载到容器中 /var/lib/mysql 目录
    ports:
      - "3308:3306"                          # 设置容器3306端口映射指定宿主机端口
    networks:
      - backend
    # restart: always

  redis:
    build:
      context: ./redis
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis:/data                 # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Redis 数据的目录挂载到容器中 /data 目录
    ports:
      - "6379:6379"                          # 设置容器6379端口映射指定宿主机端口
    networks:
      - backend
    # restart: always